DROP TABLE Clientes CASCADE CONSTRAINTS;
DROP TABLE Recompensas CASCADE CONSTRAINTS;

-- Criação da Tabela de Clientes (tabela Master)
CREATE TABLE Clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    nome VARCHAR2(100) NOT NULL,
    pontos NUMBER DEFAULT 0
);

-- Criação da Tabela de Recompensas (tabela Detail)
CREATE TABLE Recompensas (
    id_recompensa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_recompensa VARCHAR2(50) NOT NULL,  -- Ex: "Desconto" ou "Produto"
    descricao VARCHAR2(255) NOT NULL,
    data_resgate DATE,  -- Data em que a recompensa foi resgatada
    id_cliente NUMBER,  -- Cliente que resgatou a recompensa, pode ser NULL
    CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES Clientes(id_cliente)
);

-- Inserindo dados na Tabela de Clientes
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('12345678901', 'Ana Silva', 150);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('23456789012', 'Carlos Pereira', 200);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('34567890123', 'Maria Oliveira', 120);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('45678901234', 'José Souza', 180);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('56789012345', 'Luiza Alves', 90);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('67890123456', 'Pedro Martins', 210);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('78901234567', 'Fernanda Costa', 175);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('89012345678', 'Marcos Rocha', 130);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('90123456789', 'Beatriz Gomes', 240);
INSERT INTO Clientes (CPF, nome, pontos) VALUES ('01234567890', 'João Melo', 100);


-- Inserindo dados na Tabela de Recompensas
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Desconto', 'Desconto de 10% na próxima compra', TO_DATE('2024-09-15', 'YYYY-MM-DD'), 1);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Desconto', 'Desconto de 15% em produtos selecionados', TO_DATE('2024-09-20', 'YYYY-MM-DD'), 2);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Desconto', 'Desconto de 20% em qualquer item', NULL, NULL);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Camiseta personalizada', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 4);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Caneca exclusiva', NULL, NULL);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Chaveiro de metal', TO_DATE('2024-10-05', 'YYYY-MM-DD'), 6);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Desconto', 'Desconto de 5% na próxima compra', NULL, NULL);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Ecobag personalizada', TO_DATE('2024-10-10', 'YYYY-MM-DD'), 8);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Bloco de notas sustentável', NULL, NULL);
INSERT INTO Recompensas (tipo_recompensa, descricao, data_resgate, id_cliente) VALUES 
('Produto', 'Adesivos exclusivos', TO_DATE('2024-10-15', 'YYYY-MM-DD'), 10);

